// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieM2cX-lt_nit5dDnlkL1smgUozjOVjE',
    appId: '1:1092766039116:web:670f50fe73020b38b008e9',
    messagingSenderId: '1092766039116',
    projectId: 'food-delivery-app-d5dff',
    authDomain: 'food-delivery-app-d5dff.firebaseapp.com',
    storageBucket: 'food-delivery-app-d5dff.appspot.com',
    measurementId: 'G-FDBNXBQKFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4ZDbHP8lhzDHdpJvN1RE4bssSp7Bi5I',
    appId: '1:1092766039116:android:498cfefd4f9e3ba2b008e9',
    messagingSenderId: '1092766039116',
    projectId: 'food-delivery-app-d5dff',
    storageBucket: 'food-delivery-app-d5dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGoIyK9R9OzOkPOnbSfICr9lGQZZSyGdI',
    appId: '1:1092766039116:ios:eff2c46437e2b75fb008e9',
    messagingSenderId: '1092766039116',
    projectId: 'food-delivery-app-d5dff',
    storageBucket: 'food-delivery-app-d5dff.appspot.com',
    iosClientId: '1092766039116-1n3kvlvebmnfbd19shm7rec0m5vjeb5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGoIyK9R9OzOkPOnbSfICr9lGQZZSyGdI',
    appId: '1:1092766039116:ios:eff2c46437e2b75fb008e9',
    messagingSenderId: '1092766039116',
    projectId: 'food-delivery-app-d5dff',
    storageBucket: 'food-delivery-app-d5dff.appspot.com',
    iosClientId: '1092766039116-1n3kvlvebmnfbd19shm7rec0m5vjeb5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProj',
  );
}
